"""First-run model fetch for the distributed irodori-TTS.

Reads ``ledger/models.json`` (generated by ``build/make-ledger.ps1`` from the Hugging Face
API) and downloads every file of every pinned revision into one ``HF_HOME`` directory, so
that the server can later run with ``HF_HUB_OFFLINE=1``.

Design notes
------------
* **Revision pinned.** Every request carries the revision recorded in the ledger, never
  ``main``.  A repository that moves under us is a hard error, not a silent upgrade.
* **...and ``refs/main`` is written afterwards.**  A sha-pinned download leaves no
  ``refs/`` entry (huggingface_hub only writes one when the revision it was given is not
  already a commit hash), but the upstream loaders ask for these files *without* a
  revision -- i.e. for ``main``.  Under ``HF_HUB_OFFLINE=1`` that fails with
  ``LocalEntryNotFoundError`` unless ``refs/main`` points at the pinned commit, so this
  script writes it for every repository it verified whole.  See :func:`write_refs_main`.
* **Verified.** LFS files carry a real sha256 in the ledger and are hashed after download.
  ``sony/silentcipher`` stores its checkpoints as ordinary git blobs, so the API exposes
  only a git blob sha1; those files are verified by size and by that sha1 (recomputed with
  the ``blob <len>\\0`` prefix git uses), which is still a content check.
* **Progress on stdout, one JSON object per line.**  The launcher parses these; nothing else
  is written to stdout.  Human-readable notes go to stderr.
* **Nothing is written outside ``--dest``.**  The cache layout is huggingface_hub's own, so
  the same directory works as ``HF_HOME`` afterwards.

Usage
-----
    python -m ywk_fetch_models --dest "%LOCALAPPDATA%\\irodori-tts-ywk\\models"
    python -m ywk_fetch_models --dest ... --check-only

Exit codes: 0 = everything present and verified, 2 = verification failed,
3 = download or network failure, 4 = bad arguments / bad ledger.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import threading
import time
from pathlib import Path
from typing import Any, Iterable

__all__ = ["main"]

_CHUNK = 1024 * 1024


# --------------------------------------------------------------------------- output


def emit(**fields: Any) -> None:
    """Write one progress record to stdout as a single JSON line."""
    sys.stdout.write(json.dumps(fields, ensure_ascii=False) + "\n")
    sys.stdout.flush()


def note(message: str) -> None:
    sys.stderr.write(message + "\n")
    sys.stderr.flush()


# --------------------------------------------------------------------------- hashing


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        while True:
            block = fh.read(_CHUNK)
            if not block:
                break
            h.update(block)
    return h.hexdigest()


def git_blob_sha1_of(path: Path) -> str:
    """The sha1 git itself stores for a blob: sha1(b"blob <size>\\0" + content)."""
    size = path.stat().st_size
    h = hashlib.sha1()
    h.update(b"blob %d\0" % size)
    with path.open("rb") as fh:
        while True:
            block = fh.read(_CHUNK)
            if not block:
                break
            h.update(block)
    return h.hexdigest()


def verify_file(path: Path, entry: dict[str, Any]) -> tuple[bool, str]:
    """Return (ok, how). ``how`` names the check that was actually performed."""
    expected_size = int(entry.get("size") or 0)
    actual_size = path.stat().st_size
    if expected_size and actual_size != expected_size:
        return False, f"size {actual_size} != {expected_size}"

    mode = entry.get("verify") or ("sha256" if entry.get("sha256") else "size")
    if mode == "sha256" and entry.get("sha256"):
        got = sha256_of(path)
        if got != str(entry["sha256"]).lower():
            return False, f"sha256 {got} != {entry['sha256']}"
        return True, "sha256"
    if entry.get("git_blob_sha1"):
        got = git_blob_sha1_of(path)
        if got != str(entry["git_blob_sha1"]).lower():
            return False, f"git-blob-sha1 {got} != {entry['git_blob_sha1']}"
        return True, "git-blob-sha1"
    if expected_size:
        return True, "size"
    return False, "no checksum and no size in the ledger"


# --------------------------------------------------------------------------- ledger


def default_ledger_path() -> Path:
    """ledger/models.json, whether we run from the repo or from an installed app tree."""
    here = Path(__file__).resolve().parent
    for base in (here.parent, here, here.parent.parent):
        candidate = base / "ledger" / "models.json"
        if candidate.is_file():
            return candidate
    return here.parent / "ledger" / "models.json"


def load_ledger(path: Path) -> dict[str, Any]:
    if not path.is_file():
        raise FileNotFoundError(f"models ledger not found: {path}")
    with path.open("r", encoding="utf-8") as fh:
        data = json.load(fh)
    if not isinstance(data, dict) or "repos" not in data:
        raise ValueError(f"{path} is not a models ledger (no 'repos' key)")
    for repo in data["repos"]:
        if not repo.get("revision"):
            raise ValueError(f"{path}: repo {repo.get('repo')!r} has no pinned revision")
    return data


def selected_repos(data: dict[str, Any], only: Iterable[str] | None) -> list[dict[str, Any]]:
    repos = list(data["repos"])
    if not only:
        return repos
    wanted = {s.lower() for s in only}
    picked = [r for r in repos if str(r.get("role", "")).lower() in wanted or str(r["repo"]).lower() in wanted]
    if not picked:
        raise ValueError(f"no repository in the ledger matches {sorted(wanted)}")
    return picked


# --------------------------------------------------------------------------- progress


class IncompleteWatcher:
    """Report bytes landing in huggingface_hub's ``*.incomplete`` staging file.

    huggingface_hub gives no download callback we can rely on across versions, but it does
    stream every blob into ``<cache>/models--<org>--<name>/blobs/<etag>.incomplete`` first.
    Watching that one file is enough for a progress bar and touches nothing.
    """

    def __init__(self, cache_dir: Path, on_progress, interval: float = 0.5) -> None:
        self._blobs = cache_dir
        self._on_progress = on_progress
        self._interval = interval
        self._stop = threading.Event()
        self._thread: threading.Thread | None = None

    def __enter__(self) -> "IncompleteWatcher":
        self._thread = threading.Thread(target=self._run, name="ywk-fetch-progress", daemon=True)
        self._thread.start()
        return self

    def __exit__(self, *exc: object) -> None:
        self._stop.set()
        if self._thread is not None:
            self._thread.join(timeout=2.0)

    def _run(self) -> None:
        last = -1
        while not self._stop.wait(self._interval):
            size = 0
            try:
                for p in self._blobs.rglob("*.incomplete"):
                    try:
                        size = max(size, p.stat().st_size)
                    except OSError:
                        continue
            except OSError:
                continue
            if size and size != last:
                last = size
                try:
                    self._on_progress(size)
                except Exception:  # never let the reporter kill the download
                    return


# --------------------------------------------------------------------------- fetch


def fetch(
    ledger: dict[str, Any],
    repos: list[dict[str, Any]],
    dest: Path,
    check_only: bool,
    force: bool,
) -> int:
    try:
        from huggingface_hub import hf_hub_download
    except ImportError as exc:  # pragma: no cover - depends on the assembled runtime
        emit(event="error", stage="import", message=f"huggingface_hub is not importable: {exc}")
        return 3

    dest.mkdir(parents=True, exist_ok=True)
    hub_cache = dest / "hub"
    hub_cache.mkdir(parents=True, exist_ok=True)

    plan = [(repo, entry) for repo in repos for entry in repo["files"]]
    total_bytes = sum(int(entry.get("size") or 0) for _, entry in plan)
    emit(
        event="plan",
        ledger_generated=ledger.get("generated"),
        repos=[{"repo": r["repo"], "revision": r["revision"], "role": r.get("role")} for r in repos],
        total_files=len(plan),
        total_bytes=total_bytes,
        dest=str(dest),
        check_only=bool(check_only),
    )

    done_bytes = 0
    failures: list[str] = []
    bad_repos: set[str] = set()

    for repo, entry in plan:
        repo_id = str(repo["repo"])
        revision = str(repo["revision"])
        rel = str(entry["path"])
        size = int(entry.get("size") or 0)
        emit(event="file_start", repo=repo_id, path=rel, bytes=size, revision=revision)

        base = done_bytes

        def progress(current: int, _base: int = base, _size: int = size) -> None:
            emit(
                event="progress",
                repo=repo_id,
                path=rel,
                downloaded=min(current, _size) if _size else current,
                bytes=_size,
                overall_downloaded=_base + (min(current, _size) if _size else current),
                overall_bytes=total_bytes,
            )

        try:
            if check_only:
                local = _resolve_cached(hub_cache, repo_id, revision, rel)
                if local is None:
                    failures.append(f"{repo_id}:{rel} is not in the cache")
                    bad_repos.add(repo_id)
                    emit(event="file_missing", repo=repo_id, path=rel)
                    continue
            else:
                with IncompleteWatcher(hub_cache, progress):
                    local = Path(
                        hf_hub_download(
                            repo_id=repo_id,
                            filename=rel,
                            revision=revision,
                            cache_dir=str(hub_cache),
                            force_download=bool(force),
                        )
                    )
        except Exception as exc:  # network, auth, gated repo, disk full
            emit(event="error", stage="download", repo=repo_id, path=rel, message=f"{type(exc).__name__}: {exc}")
            return 3

        ok, how = verify_file(local, entry)
        if not ok:
            failures.append(f"{repo_id}:{rel} {how}")
            bad_repos.add(repo_id)
            emit(event="file_bad", repo=repo_id, path=rel, reason=how)
        else:
            emit(event="file_done", repo=repo_id, path=rel, verified=how, bytes=local.stat().st_size)
        done_bytes += size

    # Point "main" at the pinned commit for every repository that came through
    # whole.  Without this the upstream loaders -- which never pass a revision --
    # cannot find anything under HF_HUB_OFFLINE=1; see write_refs_main.
    for repo in repos:
        repo_id = str(repo["repo"])
        revision = str(repo["revision"])
        if repo_id in bad_repos:
            continue
        if check_only:
            have = read_refs_main(hub_cache, repo_id)
            if have != revision:
                failures.append(
                    f"{repo_id}: refs/main is {have!r}, expected the pinned {revision!r} "
                    "(the upstream loaders ask for main, not for the commit)"
                )
                emit(event="refs_bad", repo=repo_id, have=have, want=revision)
            continue
        try:
            changed = write_refs_main(hub_cache, repo_id, revision)
        except OSError as exc:
            failures.append(f"{repo_id}: cannot write refs/main: {exc}")
            emit(event="refs_bad", repo=repo_id, message=str(exc))
            continue
        emit(event="refs_main", repo=repo_id, revision=revision, written=changed)

    if failures:
        emit(event="done", ok=False, failures=failures, bytes=done_bytes)
        for f in failures:
            note("FAIL " + f)
        return 2
    emit(event="done", ok=True, files=len(plan), bytes=done_bytes, dest=str(dest))
    return 0


def _resolve_cached(hub_cache: Path, repo_id: str, revision: str, rel: str) -> Path | None:
    """Where huggingface_hub would have put this file, without touching the network."""
    folder = hub_cache / ("models--" + repo_id.replace("/", "--")) / "snapshots" / revision
    candidate = folder / rel
    if candidate.is_file():
        return candidate
    return None


def refs_main_path(hub_cache: Path, repo_id: str) -> Path:
    """``<hub>/models--<org>--<name>/refs/main`` -- the branch pointer."""
    return hub_cache / ("models--" + repo_id.replace("/", "--")) / "refs" / "main"


def write_refs_main(hub_cache: Path, repo_id: str, revision: str) -> bool:
    """Record the pinned commit as this repository's ``main``.

    **Why this exists.**  We download with ``revision=<commit sha>`` so that a
    repository cannot move under us.  ``huggingface_hub`` writes ``refs/<rev>``
    only when the revision it was handed is *not* already a commit hash
    (``file_download.py`` ``_cache_commit_hash_for_specific_revision``:
    ``if revision != commit_hash``), so a sha-pinned fetch leaves no ``refs/``
    entry at all.

    The upstream loaders then ask for the same files **without** a revision --
    ``snapshot_download(repo_id=...)`` (``inference_runtime.py:568``),
    ``hf_hub_download(repo_id=..., filename="weights.pth")`` (``codec.py:72``),
    ``snapshot_download(repo_id="sony/silentcipher")`` (silentcipher's
    ``server.py``) -- i.e. for ``main``.  With ``HF_HUB_OFFLINE=1`` baked in
    (design §2) and no ``refs/main`` to resolve it, every one of them raises
    ``LocalEntryNotFoundError`` on a machine whose cache we filled ourselves.

    Writing the pin here is exactly the file ``huggingface_hub`` would have left
    had it fetched ``main``; it is not a fabrication of the commit, which came
    from the ledger.
    """
    path = refs_main_path(hub_cache, repo_id)
    if path.is_file():
        try:
            if path.read_text(encoding="utf-8").strip() == revision:
                return False
        except OSError:
            pass
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(revision, encoding="utf-8")
    os.replace(tmp, path)
    return True


def read_refs_main(hub_cache: Path, repo_id: str) -> str | None:
    path = refs_main_path(hub_cache, repo_id)
    try:
        return path.read_text(encoding="utf-8").strip()
    except OSError:
        return None


# --------------------------------------------------------------------------- cli


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="ywk_fetch_models",
        description="Download the pinned Irodori-TTS model files listed in ledger/models.json.",
    )
    p.add_argument("--ledger", type=Path, default=None, help="path to models.json (default: ../ledger/models.json)")
    p.add_argument("--dest", type=Path, default=None, help="HF_HOME to fill (default: $HF_HOME)")
    p.add_argument("--repo", action="append", default=None, help="fetch only this role or repo id; repeatable")
    p.add_argument("--check-only", action="store_true", help="verify what is already there; download nothing")
    p.add_argument("--force", action="store_true", help="re-download even if the file is cached")
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    ledger_path = args.ledger or default_ledger_path()
    dest = args.dest
    if dest is None:
        env_home = os.environ.get("HF_HOME")
        if not env_home:
            emit(event="error", stage="args", message="pass --dest or set HF_HOME")
            return 4
        dest = Path(env_home)
    dest = Path(dest).expanduser()

    try:
        ledger = load_ledger(Path(ledger_path))
        repos = selected_repos(ledger, args.repo)
    except (OSError, ValueError) as exc:
        emit(event="error", stage="ledger", message=str(exc))
        return 4

    started = time.time()
    rc = fetch(ledger, repos, dest, args.check_only, args.force)
    note(f"ywk_fetch_models finished in {time.time() - started:.1f}s with exit code {rc}")
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
